name: schedule_notifications
description: A Flutter plugin to schedule Local Notifications. Ready for iOS and Android
version: 0.1.8
author: Fabricio Serralvo <fabricio.serralvo@gmail.com> Marcos Aoki <yancomul@gmail.com>
homepage: https://github.com/serralvo/schedule_notifications

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ^0.1.2

flutter:
  plugin:
    androidPackage: co.serralvo.schedulenotifications
    pluginClass: ScheduleNotificationsPlugin
